### ISSUE TITLE
Compile error on Ubuntu 22.10 x64 

### ISSUE THREAD

**Issue by valeriyvan** [apple/swift-nio-extras#199]
### Expected behavior

Package builds without errors.

### Actual behavior

Package builds with errors on Ubuntu 22.10 x64 :
```
/root/***/.build/checkouts/swift-nio-extras/Sources/CNIOExtrasZlib/include/CNIOExtrasZlib.h:17:10: error: 'zlib.h' file not found
#include <zlib.h>
         ^
```

### Steps to reproduce

1. `git clone git@github.com:apple/swift-nio-extras.git`
2. `cd swift-nio-extras/`
3. `swift build`

### If possible, minimal yet complete reproducer code (or URL to code)

n/a

### SwiftNIO-Extras version/commit hash

n/a

### Swift & OS version (output of `swift --version && uname -a`)

```
Swift version 5.8 (swift-5.8-RELEASE)
Target: x86_64-unknown-linux-gnu
Linux vapor-tg-bot 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by glbrntt** [comment]
SwifNIO Extras relies on the system providing zlib. It looks like you don't have it so you'll need to install it. On Ubuntu `apt-get install zlib1g-dev` should do it.

**Comment by valeriyvan** [comment]
Indeed, `apt-get install zlib1g-dev` solves the error.
